# Generated by Django 3.1.2 on 2021-04-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('customer_contact', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('estimated_hours', models.IntegerField()),
                ('description', models.TextField()),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Handyman.handyman')),
            ],
        ),
    ]
