# Generated by Django 3.1.2 on 2021-04-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0002_auto_20210412_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('feedback', models.CharField(max_length=200)),
                ('raview', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Handyman.contract')),
            ],
        ),
    ]
