# Generated by Django 3.1.2 on 2021-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0003_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='isPaid',
            field=models.BooleanField(default=0),
        ),
    ]
