# Generated by Django 3.1.2 on 2021-04-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0004_billing_ispaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='raview',
            new_name='review',
        ),
    ]
