# Generated by Django 3.1.2 on 2021-04-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0005_auto_20210413_0242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
