# Generated by Django 3.1.2 on 2021-04-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0006_delete_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
