# Generated by Django 3.1.2 on 2021-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0008_auto_20210413_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='isPaid',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
