# Generated by Django 3.1.2 on 2021-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0009_auto_20210413_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='total_hours',
            field=models.IntegerField(blank=True),
        ),
    ]
