# Generated by Django 3.1.7 on 2021-04-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handyman', '0011_auto_20210413_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email1',
            field=models.EmailField(default='handy@gmail.com', max_length=50),
        ),
    ]
